name: shoe_shop_complete
description: A complete shoe shop application with Firebase backend for mobile and web
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  cloud_firestore: ^5.6.11

# Web-specific fixes (if you're using Flutter Web)
  firebase_auth_web: ^5.9.0
  firebase_storage_web: ^3.7.0

  # UI & Animations
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  
  # Image & File Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.2
  
  # Platform specific
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700